name: Publish Python Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 20

      - name: Fetch tags
        run: git fetch --tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade build twine
          python -m pip install -r requirements.txt

      - name: Fix python-version
        run: |
          python syncVersionWithTag.py

      - name: Build the package
        run: |
          make

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/*

